monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: warning
            handler: grouped
            excluded_http_codes: [404, 405]
            channels: ['!event']
        grouped:
            type: group
            members: [nested, stderr]
        nested:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            max_files: 10
        stderr:
            type: stream
            path: 'php://stderr'
            level: info
            formatter: json_formatter
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine']