monolog:
    channels: ['scheduler', 'deprecation']
    handlers:
        main:
            type: fingers_crossed
            action_level: warning
            handler: grouped
            excluded_http_codes: [404, 405]
            channels: ['!event']
        grouped:
            type: group
            members: [nested, stderr]
        nested:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            max_files: 10
        stderr:
            type: stream
            path: 'php://stderr'
            level: info
            formatter: monolog.formatter.json_formatter
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine']
        scheduler:
            type: group
            members: [scheduler_file, scheduler_stderr]
            channels: ['scheduler']
        scheduler_file:
            type: stream
            path: '%kernel.logs_dir%/scheduler.log'
            level: info
            formatter: monolog.formatter.json_formatter
        scheduler_stderr:
            type: stream
            path: 'php://stderr'
            level: info
            formatter: monolog.formatter.json_formatter

when@prod:
    monolog:
        channels: ['scheduler', 'deprecation']
        handlers:
            main:
                type: fingers_crossed
                action_level: info
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ['!deprecation']
                buffer_size: 50
            nested:
                type: stream
                path: 'php://stderr'
                level: debug
                formatter: monolog.formatter.json_formatter
            console:
                type: console
                process_psr_3_messages: false
                channels: ['!event', '!doctrine']
            deprecation:
                type: stream
                channels: [deprecation]
                path: 'php://stderr'
                formatter: monolog.formatter.json_formatter
            scheduler:
                type: stream
                path: 'php://stderr'
                level: info
                formatter: monolog.formatter.json_formatter
                channels: ['scheduler']